[package]
name = "xmr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-argon2 = "1.0"
blake2  = "0.10.6"
aes-prng = "0.2.0"
aes = "0.8.2"